name: Android Emulator Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  emulator-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up JDK 17 (required for Android SDK tools)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 11076708
          log-accepted-android-sdk-licenses: false
          packages: >-
            tools
            platform-tools
            emulator
            build-tools;35.0.0
            system-images;android-35;google_apis_playstore;x86_64
            platforms;android-35

      # Create an Android Virtual Device (AVD)
      - name: Create AVD
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd --name test_avd --package "system-images;android-35;google_apis_playstore;x86_64" --device "medium_phone" --force
          $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager list avd

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: "Set avd home"
        run: echo "ANDROID_AVD_HOME=/home/runner/.config/.android/avd" >> $GITHUB_ENV

      # Start the Android Emulator
      - name: Start Emulator
        run: |
          nohup $ANDROID_HOME/emulator/emulator -avd test_avd -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -verbose &
          adb wait-for-device

      # Check Emulator Status
      - name: Verify Emulator Boot
        run: adb shell getprop init.svc.bootanim | grep -e 'stopped'

      # Run Debugging Commands
      - name: Run Debug Commands
        run: |
          adb devices
          adb shell getprop ro.build.version.release
          adb shell uptime

      # Stop the Emulator
      - name: Stop Emulator
        run: adb emu kill
