name: Android Emulator Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  emulator-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up JDK 17 (required for Android SDK tools)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: >-
            tools
            platform-tools
            emulator
            build-tools;35.0.0
            system-images;android-35;google_apis_playstore;x86_64
            platforms;android-35

      # Create an Android Virtual Device (AVD)
      - name: Create AVD
        run: echo "no" | avdmanager create avd -n test_avd -k "system-images;android-35;google_apis_playstore;x86_64"

      # Start the Android Emulator
      - name: Start Emulator
        run: |
          $NADROID_HOME/emulator/emulator -avd test_avd -no-window -gpu swiftshader_indirect -verbose &
          adb wait-for-device

      # Check Emulator Status
      - name: Verify Emulator Boot
        run: adb shell getprop init.svc.bootanim | grep -e 'stopped'

      # Run Debugging Commands
      - name: Run Debug Commands
        run: |
          adb devices
          adb shell getprop ro.build.version.release
          adb shell uptime

      # Stop the Emulator
      - name: Stop Emulator
        run: adb emu kill
